services:
  midas-api:
    image: midas-api:1.0.0-SNAPSHOT
    build:
      context: ../..
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: midas
      QUARKUS_DATASOURCE_PASSWORD: changeit
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/midas
      QUARKUS_DATASOURCE_JDBC_DRIVER: org.postgresql.Driver
    healthcheck:
      test: ["CMD-SHELL", "curl -f -I http://midas-api:8080/api/v1/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "8080:8080"

networks:
  default:
    name: midas-shared-network
