services:
  midas-api:
    image: midas-api:1.0.0-SNAPSHOT
    build:
      context: ../..
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: midas
      QUARKUS_DATASOURCE_PASSWORD: changeit
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/midas
      QUARKUS_DATASOURCE_JDBC_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"

networks:
  default:
    name: midas-shared-network
